In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('train.csv', delimiter=";")
df

,ID,review_content,review_title,review_stars,product,Target
0,0,En appelant un acheteur pour demander si l'écr...,La Police s'inscrit en acheteur privé sur Pric...,5,2fbb619e3606f9b7c213e858a109cda771aa2c47ce50d5...,0
1,1,"Alors, là, on a affaire au plus grand Navet ja...",Chef D'Oeuvre Absolu en vue...,5,7b56d9d378d9e999d293f301ac43d044cd7b4786d09afb...,1
2,2,Effet garanti sur la terrase. Ils donnent immé...,Effet garanti sur la terrase. Ils donnent immé...,3,7b37bf5dcb2fafd9229897910318a7dfa11a04ca36893c...,0
3,3,tres bon rapport qualite prix tre pratique en ...,bon produit,4,77d2dbd504b933ab3aaf7cb0cd81c22f7c3549012f4f88...,1
4,4,Ordinateur de bureau trés bien pour quelqu'un ...,Apple Power MAC G4,3,f574512e7d2dd1dd73c7f8f804bf16f14c932c5651a01b...,1
...,...,...,...,...,...,...
59995,59995,"Bonjour, je suis intereser par votre annonce e...",moto,5,675ebad7919f00b9cb4adb1469054240d8c76018dc27d2...,1
59996,59996,Voline nous raconte en détail un aspect beauco...,Un témoignage fort contre l'oubli,4,a15a274f7d11ed085c745246bb078098e501198956eeeb...,1
59997,59997,D'une bonne matière flexible ce double saura s...,Double plaisir,5,32a26794184ba74118c581b1659e85c2133227e18e97c2...,1
59998,59998,très bien pour compléter des collections de fè...,tres bien,5,018af320f0b08e59032011e0bbc68d42f9486833c0482e...,1
59999,59999,"Retrouvez Louis De funès, Michel Modo, Guy Gro...",Un Classique de De Funès !,5,89875e949f97865a14907a6a6f6da869836a0004adabf0...,0

In [10]:
df.head()

,ID,review_content,review_title,review_stars,product,Target
0,0,En appelant un acheteur pour demander si l'écr...,La Police s'inscrit en acheteur privé sur Pric...,5,2fbb619e3606f9b7c213e858a109cda771aa2c47ce50d5...,0
1,1,"Alors, là, on a affaire au plus grand Navet ja...",Chef D'Oeuvre Absolu en vue...,5,7b56d9d378d9e999d293f301ac43d044cd7b4786d09afb...,1
2,2,Effet garanti sur la terrase. Ils donnent immé...,Effet garanti sur la terrase. Ils donnent immé...,3,7b37bf5dcb2fafd9229897910318a7dfa11a04ca36893c...,0
3,3,tres bon rapport qualite prix tre pratique en ...,bon produit,4,77d2dbd504b933ab3aaf7cb0cd81c22f7c3549012f4f88...,1
4,4,Ordinateur de bureau trés bien pour quelqu'un ...,Apple Power MAC G4,3,f574512e7d2dd1dd73c7f8f804bf16f14c932c5651a01b...,1

In [11]:
df.describe()

                 ID  review_stars        Target
count  60000.000000  60000.000000  60000.000000
mean   29999.500000      4.308667      0.554850
std    17320.652413      1.151512      0.496987
min        0.000000      1.000000      0.000000
25%    14999.750000      4.000000      0.000000
50%    29999.500000      5.000000      1.000000
75%    44999.250000      5.000000      1.000000
max    59999.000000      5.000000      1.000000

In [7]:
df.columns

Index(['ID', 'review_content', 'review_title', 'review_stars', 'product',
       'Target'],
      dtype='object')

In [9]:
X = df[['ID', 'review_content', 'review_title', 'review_stars', 'product']]
y = df['Target']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

X_train, X_test, y_train, y_test

(          ID                                     review_content  \
 25799  25799  robe jolie arrivé rapidement finition pas trop...
 56172  56172  assez decu de cet article car pour un professi...
 7098    7098  déja que j'aime pas les miniatures alors je tr...
 2602    2602  Ampli tuner avec lecteur de K7. Puissance et q...
 15335  15335  Voluptueux, rouge comme la braise, sensuel !\n...
 ...      ...                                                ...
 54343  54343  Ces bretelles correspondent parfaitement à mon...
 38158  38158  Très bon livre pour celui qui rêve beaucoup !\...
 860      860  Jeux sympathiques et dans les prix, ne pas vou...
 15795  15795  TomTom en parfait état de marche, utiliser deu...
 56422  56422  J'ai acheté les verres et le bec verseur donc ...

                    review_title  review_stars  \
 25799             robe takchita             3
 56172                 pas super             2
 7098              le plus moche             1
 2602        Original ! Et Rare.             4
 15335           Très voluptueux             5
 ...                         ...           ...
 54343  Très utile et esthétique             5
 38158            Très satisfait             5
 860                 Sympathique             4
 15795      TOMTOM ONE V3 EUROPE             4
 56422                      Joli             4

                                                  product
 25799  5568d0e86c5cc400ce85779617c698e017558dc803e75d...
 56172  b96575e7324855f965ddab1da54dfde287aa16f17fe550...
 7098   edf1ef8c7d2301e54f836b900b1ad796109baa6bc712cc...
 2602   7b105b87b09f3f0c5986034766e21f7eac667968b612be...
 15335  2e7adb94336a1a7b340e0fa14faa7024866273ff40a994...
 ...                                                  ...
 54343  397d3c05fb6ce56a7d7fecde8ad41f7cf3daa342479746...
 38158  239198b333e7e37877d5ecc9efc42190b06f55b7a0845d...
 860    0cbe7d8af559003cb1b831020876baa23bc3f0195298a8...
 15795  a403b1ddc321ef1c5b83f02400d2cb465e0c00972729ed...
 56422  cc265458608990019622c0550074b58d878aec9ab03f1d...

 [40200 rows x 5 columns],
           ID                                     review_content  \
 12628  12628  cette est tres fiable un tout petit peu fragil...
 37730  37730  magnifique chaussons bebe reborne fait main tr...
 39991  39991  Ici ça fait dix ans que j'en ai un comme celui...
 8525    8525  très bien pour compléter les collections des a...
 8279    8279  super son, ultra leger, bon casque. très prati...
 ...      ...                                                ...
 2715    2715  Même si ce model et 1988  CB Superstar 360FM j...
 11309  11309  Ce magnifique manteau est bien chaud et en plu...
 20807  20807  Excellent. Les personnages principaux sont des...
 6681    6681  aaaaaaaaaaaaaaaa aaaa aaaa aaa aaaaa aaaaaa aa...
 44046  44046  il est vrèment très intéréssant ce téléphone j...

                                             review_title  review_stars  \
 12628                                          a acheter             3
 37730                           petit pied bien au chaud             5
 39991                                              Extra             5
 8525                                               sympa             4
 8279                                          trop top !             4
 ...                                                  ...           ...
 2715                                   VRAIMENT TRES BON             5
 11309                                      BEAU ET CHAUD             5
 20807  3 tome de l'intégrale de cette incontournable ...             4
 6681                                                hhhh             5
 44046                                     recommandation             5

                                                  product
 12628  c11208149fadb3a89eb2794e28194a269641fdf69cbcf5...
 37730  0eecff93e45bba4b9f3682f4be9febdfabad63107f32b0...
 39991  e62a37467948b9eac64e49a9263642f71acddf49a9695f...
 8525   7b783306b8fac4938271da8bf63a790226c0629a1bf511...
 8279   89f9e70d7a72a2542dca79484bc6b1e2ebcf77c637da6e...
 ...                                                  ...
 2715   8b36435c6f5fc9496b61591ee412fc4a89e9ede1c0b0a8...
 11309  14ade7b25d75ca38c66d50bb7336bb99102ab2a5a73c27...
 20807  e30871132a4785558c5ec98e6f7ea74d11f9e0a2ff37e7...
 6681   c7168b30ec109ddf2383d32f3147e16f9ae7dabca2ce7a...
 44046  46daee25cc096fcea34ad8f6fc280f897b99489bbc7995...

 [19800 rows x 5 columns],
 25799    0
 56172    0
 7098     0
 2602     1
 15335    1
         ..
 54343    0
 38158    1
 860      1
 15795    1
 56422    0
 Name: Target, Length: 40200, dtype: int64,
 12628    0
 37730    1
 39991    1
 8525     1
 8279     1
         ..
 2715     1
 11309    1
 20807    1
 6681     1
 44046    1
 Name: Target, Length: 19800, dtype: int64)